export const REQUEST_POPULAR_FILMS = 'REQUEST_POPULAR_FILMS'
export const RECEIVE_POPULAR_FILMS = 'RECEIVE_POPULAR_FILMS'

export const SHOW_MORE_POPULAR_FILMS = 'SHOW_MORE_POPULAR_FILMS'
export const SHOW_LESS_POPULAR_FILMS = 'SHOW_LESS_POPULAR_FILMS'

export const REQUEST_FILM = 'REQUEST_FILM'
export const RECEIVE_FILM = 'RECEIVE_FILM'

export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'

export const REQUEST_POPULAR_LISTS = 'REQUEST_POPULAR_LISTS'
export const RECEIVE_POPULAR_LISTS = 'RECEIVE_POPULAR_LISTS'

export const REQUEST_RECENT_LISTS = 'REQUEST_RECENT_LISTS'
export const RECEIVE_RECENT_LISTS = 'RECEIVE_RECENT_LISTS'

export const REQUEST_RELATED_LISTS = 'REQUEST_RELATED_LISTS'
export const RECEIVE_RELATED_LISTS = 'RECEIVE_RELATED_LISTS'

export const REQUEST_LIST = 'REQUEST_LIST'
export const RECEIVE_LIST = 'RECEIVE_LIST'

export const REQUEST_ADD_LIST = 'REQUEST_ADD_LIST'
export const RECEIVE_ADD_LIST = 'RECEIVE_ADD_LIST'

export const REQUEST_REMOVE_LIST = 'REQUEST_REMOVE_LIST'
export const RECEIVE_REMOVE_LIST = 'RECEIVE_REMOVE_LIST'

export const REQUEST_EDIT_LIST = 'REQUEST_EDIT_LIST'
export const RECEIVE_EDIT_LIST = 'RECEIVE_EDIT_LIST'

export const REQUEST_EDIT_POSTER = 'REQUEST_EDIT_POSTER'
export const RECEIVE_EDIT_POSTER = 'RECEIVE_EDIT_POSTER'

export const INVALIDATE_POPULAR_LISTS = 'INVALIDATE_POPULAR_LISTS'
export const INVALIDATE_RECENT_LISTS = 'INVALIDATE_RECENT_LISTS'
export const INVALIDATE_RELATED_LISTS = 'INVALIDATE_RELATED_LISTS'
